/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerAnnouncementsRouteImport } from './routes/manager/announcements'
import { Route as ManagerChatRouteImport } from './routes/manager/chat'
import { Route as ManagerInboxRouteImport } from './routes/manager/inbox'
import { Route as ManagerMeetingsRouteImport } from './routes/manager/meetings'
import { Route as ManagerReportsRouteImport } from './routes/manager/reports'
import { Route as ManagerSpacesRouteImport } from './routes/manager/spaces'
import { Route as ManagerTasksRouteImport } from './routes/manager/tasks'
import { Route as ManagerTeamRouteImport } from './routes/manager/team'
import { Route as ManagerUsersRouteImport } from './routes/manager/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnnouncementsRoute = ManagerAnnouncementsRouteImport.update({
  id: '/manager/announcements',
  path: '/manager/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerChatRoute = ManagerChatRouteImport.update({
  id: '/manager/chat',
  path: '/manager/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerInboxRoute = ManagerInboxRouteImport.update({
  id: '/manager/inbox',
  path: '/manager/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerMeetingsRoute = ManagerMeetingsRouteImport.update({
  id: '/manager/meetings',
  path: '/manager/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/manager/reports',
  path: '/manager/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSpacesRoute = ManagerSpacesRouteImport.update({
  id: '/manager/spaces',
  path: '/manager/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/manager/tasks',
  path: '/manager/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersRoute = ManagerUsersRouteImport.update({
  id: '/manager/users',
  path: '/manager/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/inbox': typeof ManagerInboxRoute
  '/manager/meetings': typeof ManagerMeetingsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/spaces': typeof ManagerSpacesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/inbox': typeof ManagerInboxRoute
  '/manager/meetings': typeof ManagerMeetingsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/spaces': typeof ManagerSpacesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/chat': typeof ManagerChatRoute
  '/manager/inbox': typeof ManagerInboxRoute
  '/manager/meetings': typeof ManagerMeetingsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/spaces': typeof ManagerSpacesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manager/announcements'
    | '/manager/chat'
    | '/manager/inbox'
    | '/manager/meetings'
    | '/manager/reports'
    | '/manager/spaces'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/users'
    | '/admin/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manager/announcements'
    | '/manager/chat'
    | '/manager/inbox'
    | '/manager/meetings'
    | '/manager/reports'
    | '/manager/spaces'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/users'
    | '/admin'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/manager/announcements'
    | '/manager/chat'
    | '/manager/inbox'
    | '/manager/meetings'
    | '/manager/reports'
    | '/manager/spaces'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/users'
    | '/admin/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManagerAnnouncementsRoute: typeof ManagerAnnouncementsRoute
  ManagerChatRoute: typeof ManagerChatRoute
  ManagerInboxRoute: typeof ManagerInboxRoute
  ManagerMeetingsRoute: typeof ManagerMeetingsRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSpacesRoute: typeof ManagerSpacesRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ManagerUsersRoute: typeof ManagerUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/announcements': {
      id: '/manager/announcements'
      path: '/manager/announcements'
      fullPath: '/manager/announcements'
      preLoaderRoute: typeof ManagerAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/chat': {
      id: '/manager/chat'
      path: '/manager/chat'
      fullPath: '/manager/chat'
      preLoaderRoute: typeof ManagerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/inbox': {
      id: '/manager/inbox'
      path: '/manager/inbox'
      fullPath: '/manager/inbox'
      preLoaderRoute: typeof ManagerInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/meetings': {
      id: '/manager/meetings'
      path: '/manager/meetings'
      fullPath: '/manager/meetings'
      preLoaderRoute: typeof ManagerMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/spaces': {
      id: '/manager/spaces'
      path: '/manager/spaces'
      fullPath: '/manager/spaces'
      preLoaderRoute: typeof ManagerSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/manager/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/manager/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManagerAnnouncementsRoute: ManagerAnnouncementsRoute,
  ManagerChatRoute: ManagerChatRoute,
  ManagerInboxRoute: ManagerInboxRoute,
  ManagerMeetingsRoute: ManagerMeetingsRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSpacesRoute: ManagerSpacesRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ManagerUsersRoute: ManagerUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
